version: '3.5'
services:
  game-service:
    build: .
    image: demo/game-service
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      SERVICE_PORT: ${SERVICE_PORT:-8080}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: